on: push
name: Deploy on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
    - name: Use Yarn ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    
    - name: ync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ssh.wolfed.me:22
        username: wolfed.me
        password: ${{ secrets.ftp_password }}
        local-dir: ./wishlist/
