on: push
name: Deploy on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global yarn
    - run: yarn
    - run: yarn run build
    
    - name: ync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ssh.wolfed.me:22
        username: wolfed.me
        password: ${{ secrets.ftp_password }}
        local-dir: ./wishlist/
