on:
  push:
    branches:
      - main
name: Deploy on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - run: yarn install && yarn build
      - name: Push to SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.wolfed.me
          port: 21
          username: wolfed.me
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./wishlist/
          local-dir: ./build/
          log-level: verbose
