on: push
name: Deploy on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Build
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn build
    - name: Push to SFTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ssh.wolfed.me:22
        username: wolfed.me
        password: ${{ secrets.ftp_password }}
        local-dir: ./wishlist/
